apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: {{ .Values.flask.service.type }}
  selector:
    app: flask-app
  ports:
    - port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.service.port }}
